# Configurações comuns (todos os ambientes)
spring:
  application:
    name: kafka-springboot-api-demo
# =================================================
# AMBIENTE DE DESENVOLVIMENTO (dev)
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
  servlet:
    context-path: /dev-api
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.minhaapp: TRACE
# =================================================
datasource:
  url: jdbc:h2:mem:devdb
  username: sa
  password: ''
  driver-class-name: org.h2.Driver
jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: true
  properties:
    hibernate.format_sql: true
kafka-springboot-api-demo:
  cache-enabled: false
  debug-endpoints: true
  external-service:
    url: https://sandbox.api.com
    timeout: 5000
